
 <div class="admin_menu_box">
             <div class="">
               				<div class="manage-inventory-right-panel">
   <div class="middle">

<span class="err_hide"></span>
<h3>Agent Creation Form</h3>
 <div class="tab">
    	<ul>
           <li><a style="cursor:pointer" class="active ">Create Agent</a></li>
            <li><a style="cursor:pointer" href="<?php echo $this->url('rctransfer',array("action"=>"login")) ?>" >RCT Log-in</a></li>
			 <li><a style="cursor:pointer" href="<?php echo $this->url('rctransfer',array("action"=>"view")) ?>" >RCT Edit</a></li>
        </ul>
    </div>	 
 <div class="tab-Available">
        <div class="add-inventory-tab-content">
<?php if(count($flashMessages)) : ?>
    <div class="row" >
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button">
                ×
            </button>
            <ul>
                <?php foreach ($flashMessages as $msg) : ?>
                    <li><?php echo $msg; ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<div class="grid_head">


</div>
<span class="tab_manage_container" style="display:block">
<?php $form->prepare(); // The correct enctype is set here ?>
		<?php echo $this->form()->openTag($form); ?>
		 <?php echo $this->formHidden($form->get('agent_id')); ?>	
		 <table cellpadding="12" cellspacing="12" width="100%">
                
                <tbody>
				<tr>
                    <td><span class="label-text">Agent Name &nbsp; &nbsp;</span><?php echo $this->formText($form->get('agent_name')); ?></td>
                    <td><span class="label-text">Representative&nbsp;&nbsp;</span><?php echo $this->formText($form->get('representative')); ?></td>
					<td><span class="label-text">Agent ID&nbsp;&nbsp;</span> <?php echo $this->formText($form->get('agent_number')); ?></td>
                </tr>
				<tr>
                    <td><span class="label-text">Mobile&nbsp;&nbsp;</span><?php echo $this->formText($form->get('agent_mobile')); ?></td>
					<td><span class="label-text">Alternate Phone&nbsp;&nbsp;</span><?php echo $this->formText($form->get('agent_alt_mobile')); ?></td>
					<td><span class="label-text">Email&nbsp;&nbsp;</span><?php echo $this->formText($form->get('agent_email')); ?></td>
                </tr>
			
				<tr>
                    <td colspan="2"><span class="label-text">Address&nbsp;&nbsp;</span><?php echo $this->formTextarea($form->get('agent_address')); ?>	</td>
				</tr>
				<tr>
                    <td><span class="label-text">State&nbsp;&nbsp;</span><?php echo $this->formSelect($form->get('agent_state')); ?></td>
                    <td><span class="label-text">City&nbsp;&nbsp;</span><?php echo $this->formSelect($form->get('agent_city')); ?></td>
					<td><span class="label-text">Pin code&nbsp;&nbsp;</span><?php echo $this->formText($form->get('agent_pin_code')); ?></td>
                </tr>
				</tbody>
			</table>
			<input type="submit" id="addimagesave" class="add-enventry-save" value="Save">
<?php echo $this->form()->closeTag(); ?>
</span>
</div>
</div>
 </div>
    
</div>
             </div>
    </div>
<script type="text/javascript">
  $(document).ready(function() {
  $('[name="customer_dob"]').datepicker({
            format: "yyyy-mm-dd"
        }).on('changeDate', function(e){
		$(this).datepicker('hide');
	});
	
	$("#save-agent").submit( function(){
		 var sEmail = $('#agent_email').val();
		if (!validateEmail(sEmail)) {
			alert('Invalid Email Address');
			return false;
		}
		var phone = $('#agent_mobile').val();
		if (!validatePhone(phone)) {
			alert('Invalid Mobile No');
			return false;
		}
	});
	
  });
function validateEmail(emailAddress){
	 var pattern = /^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/i;
    return pattern.test(emailAddress);
}

function validatePhone(phone)
{
	var pattern = /[0-9]{10}/;
	 return pattern.test(phone);
}
</script>