<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Manage Make Model Variant
        	<div>
       			
            
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
			<table width="100%" border="0">
    <tbody>
        <tr>
            <td width="22%" align="right" height="20"><a href="<?php echo $this->url('mmv',array('action' => "export")) ?>" class="link_org3">Export MMV</a></td>
						
        </tr>
    </tbody>
</table>
<br>
    </div>	


	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        
    <!-- The file upload form used as target for the file upload widget -->
    <form id="frmMMV" name="frmMMV" action="<?php echo $this->url('mmv',array('action' => "add")) ?>" method="POST" enctype="multipart/form-data">
        
		<div class="basic-car-detail-header">Upload Makemodel variant file</div>
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				
				<tr>
                	<td>
					<span class="label-text">Select File*: </span>
					<input type="file" name="upload_mmv" id="upload_mmv">
						
                    </td>
					
                    <td>
					
                    </td><td>&nbsp;
                    </td>
                </tr>
            </tbody></table>
			<input type="submit" id="save" class="add-enventry-save" value="Save">
		</div>
    </form>
   
</div>
        <p></p>
    

	 </div>
	 </div>
</div>