<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Add Buyer Enquiry 
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
     <div class="tab">
    	
    </div>	
	<div class="tab-Available">
        <div class="add-inventory-tab-content">
		<?php $form->prepare(); // The correct enctype is set here ?>
		<?php echo $this->form()->openTag($form); ?>
			<input type="hidden" name="enq_id" id="enq_id" value="<?php echo $arrData['enq_id']; ?>">
			<input type="hidden" name="customer_id" id="customer_id" value="<?php echo $arrData['customer_id']; ?>">
			<input type="hidden" name="mmv_id" id="mmv_id" value="">
        <!-- Car Details -->
		
		
        <div class="sub-content">
		
		 
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				<tr>
                    <td>
                        
                        <div id="makediv_img" style="display:none;" class="makemodelversiondiv">
                            <img src="<?php echo $this->basePath(); ?>/images/loader.gif" class="makemodelversionimg">                        </div>
                            <span class="select-popup-container">
								 
                                <select name="year" id="year" class="car-make-select-small select-mrg-10 select-make">
                                    <option value="">Select Year</option>
									<?php echo $end_year = date("Y");
									for($intY = $end_year; $intY >= $start_year; $intY--)
									{ 
										?><option class="jyear" value="<?php echo $intY; ?>"><?php echo $intY; ?></option><?php
									}
									?>
                                                                            
                                                                            
                                                                 
                                </select>
                            </span>                       </td>
                    <td>&nbsp;</td>
			<td>&nbsp;</td>
                </tr>
				<tr>
                    <td>
                        <div id="makediv_img" style="display:none;" class="makemodelversiondiv">
                            <img src="<?php echo $this->basePath(); ?>/images/loader.gif" class="makemodelversionimg">                        </div>
                        <span class="select-popup-container">
                            <span class="label-text">Make*: </span>
                            <span class="makeerror errortext"></span>
                            
                            <select name="make" id="make" class="car-make-select" required>
                                <option value="" class="jMake">Select                                </option>
                                                                                            </select>  
                        </span></td>
                    <td>
                        <div id="modeldiv_img" style="display:none;" class="makemodelversiondiv">
                            <img src="<?php echo $this->basePath(); ?>/images/loader.gif" class="makemodelversionimg">                        </div>
                        
                        <span class="select-popup-container">
                            <span class="label-text">Model*: </span>
                            <span class="modelerror errortext"></span>
                            <select name="model" id="model" class="car-make-select" required>
                                <option value="">Model</option>
                                                             </select>
                        </span></td>
                    <td>
                        <div id="versiondiv_img" style="display:none;" class="makemodelversiondiv">
                            <img src="<?php echo $this->basePath(); ?>/images/loader.gif" class="makemodelversionimg">                        </div>
                        
                       
                        <span class="select-popup-container">
                            <span class="label-text">Variant*: </span>
                            <span class="varianterror errortext"></span>
                            <select name="variant" id="variant" class="car-make-select" required>
                                <option value="">Variant</option>
                                                            </select>                               
                        </span>                    </td>
                </tr>
				<tr>
                	
				
                	<td>					 
					<span class="label-text">Email: </span>
					 <?php echo $this->formText($form->get('email')); ?>
					 </td>
					 <td>
					 <span class="label-text">Mobile: </span>
					 <?php echo $this->formText($form->get('mobile')); ?>	
                    </td>
					<td>
					<input type="button" name="get-customer" id="get-customer" value="Check Customer Exist">
					
					</td>
               </tr>
				<tr>
				<td>					 
					<span class="label-text">Customer Name: </span>
					 <?php echo $this->formText($form->get('name')); ?>	
                    </td>
					
                	<td colspan="2">					 
					<span class="label-text">Address: </span>
					 <?php echo $this->formTextArea($form->get('customer_address')); ?>	
                    </td>
					
                 </tr>
				<tr>
                	
                	<td>					 
					<span class="label-text">State: </span>
					 <?php echo $this->formSelect($form->get('customer_state')); ?>	
                    </td>
					
					
                	<td>					 
					<span class="label-text">City: </span>
					 <?php echo $this->formSelect($form->get('customer_city')); ?>	
                    </td>
				
                	<td>					 
					<span class="label-text">Pin Code: </span>
					 <?php echo $this->formText($form->get('customer_pin')); ?>	
                    </td>
					
               </tr>
				<tr>
                	<td>					 
					<span class="label-text">Gender: </span>
					 <?php echo $this->formSelect($form->get('gender')); ?>	
                    </td>
					
               
                	<td>					 
					<span class="label-text">Profession: </span>
					 <?php echo $this->formText($form->get('profession')); ?>	
                    </td>
					
               
                	<td>					 
					<span class="label-text">Annual Income: </span>
					 <?php echo $this->formText($form->get('annual_income')); ?>	
                    </td>
					
                 </tr>
				<tr>	
					
               
                	<td colspan="2">					 
					<span class="label-text">Comments: </span>
					 <?php echo $this->formTextArea($form->get('comments')); ?>	
                    </td>
					
                </tr>
				<tr>
                	<td>					 
					<span class="label-text">Status: </span>
					 <?php echo $this->formSelect($form->get('status')); ?>	
                    </td>
					</tr>
				
               
            </tbody></table>
			<input type="submit" id="addimagesave" class="add-enventry-save" value="Save">
		</div>
		<?php echo $this->form()->closeTag(); ?>
	 </div>
	 </div>
</div>
</div>
</div>