<html><head>
<style type="text/css">
@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide{display:none !important;}ng\:form{display:block;}.ng-animate-block-transitions{transition:0s all!important;-webkit-transition:0s all!important;}
</style>
</head>
<body cz-shortcut-listen="true">
<pre style="word-wrap: break-word; white-space: pre-wrap;">
<?php echo $strDisplay; ?>
</pre><spots-wrapper></spots-wrapper></body></html>