<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Inventory Images
        	<div class="add-image">
       			
              <a href="<?php echo $this->url('inventory',array('action' => "index",'id'=>'1')) ?>">Back </a> 
        </div>	
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;display:none;">Please Rectify The Errors In Red.</div>
		<div class="tab">
    	<ul>
           <li><a style="cursor:pointer" href="<?php echo $this->url('inventory',array('action' => "edit",'id'=>$stockid)) ?>">Car Details</a></li>
            <li><a style="cursor:pointer" class="active " >Image Manager</a></li>
        </ul>
    </div>	
	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        <div class="popup-tab popup-tab-margin">
            	<ul>
                	<li><a href="<?php echo $this->url('inventory',array('action' => "image-list",'id'=>$stockid))?>">Upload Photos</a></li>
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-sort",'id'=>$stockid))?>">Sort Photos</a></li> 
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-view",'id'=>$stockid))?>">View Photos</a></li>
                </ul>
            </div> 
			<br><br>
			<?php 
			$form->setAttribute('action', $this->url('inventory', array('action' => 'add-image','id'=>$stockid)));
			$form->prepare(); // The correct enctype is set here ?>
		<?php echo $this->form()->openTag($form); ?>
			
        <!-- Car Details -->
		
        <div class="sub-content">
		 <div style="color:green;text-align:center;padding-bottom: 10px;
    text-align: center;">You can upload images of size greater than 25kb and less than 8MB</div>
		 <div class="basic-car-detail-header">Image Upload</div>
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				
				<tr>
                	<td>
					 <?php
						
					 $fileElement = $form->get('image-file'); ?>
					<span class="label-text">Select Image*: </span>
					
                    	<?php echo $this->formFile($fileElement); ?>
						<?php echo $this->formElementErrors($fileElement); ?>
						
                    </td>
					
                    <td>
					
                    </td><td>&nbsp;
                    </td>
                </tr>
				
            </tbody></table>
			<input type="submit" id="addimagesave" class="add-enventry-save" value="Save">
		</div>
	<?php echo $this->form()->closeTag(); ?>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="frmImageList" name="frmImageList" action="" method="POST" enctype="multipart/form-data">
     <input type="hidden" name="stockid" id="stockid" value="<?php echo $stockid; ?>">   
        <!-- The loading indicator is shown during file processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped" width="100%"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
		
		<tr class="template-download" style="display: table-row;">
        
            <td class="preview">
			
				
				<button type="button" class="set-profile-img btn btn-danger setprofile ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary">
                    <i class="icon-plus icon-white"></i>
                    <span class="ui-button-text">Set as profile</span>
                </button>
			 
			</td>
            <td class="name">
               <button type="button" class="btn-save-tag btn btn-danger setprofile ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary">
                    <i class="icon-plus icon-white"></i>
                    <span class="ui-button-text">Save Tag</span>
                </button>
            </td>
            <td class="size"><span></span></td>
            <td colspan="2"></td>
        
        <td class="delete">
             <button type="button" class="btn btn-delete-selected btn-danger delete ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary" role="button" aria-disabled="false"><span class="ui-button-icon-primary ui-icon ui-icon-trash"></span><span class="ui-button-text">
                    <i class="icon-trash icon-white"></i>
                    <span>Delete Selected</span>
                </span></button>
		 </td>
		   <td>
                <input type="checkbox" id="chk_all_post" name="chk_all_post" value="false" class="toggle">
        </td>
    </tr>
		<?php 
			$cnt = 0;
			foreach($objStockImages as $stockImage) { ?>
			<?php
			if (file_exists($config['image_absolute_path']."stock/crop/".$stockImage->image_name)) {
				$image_path = $config['image_path']."stock/crop/";
				$filesize = filesize($config['image_absolute_path']."stock/crop/".$stockImage->image_name);
			}
			else
			{
				$filesize = filesize($config['image_absolute_path']."stock/".$stockImage->image_name);
				$image_path = $config['image_path']."stock/";
			}
			?>
		<tr class="template-download" style="display: table-row;">
        
            <td class="preview">
			
			 
			 <input class="profileimage" name="profileimage" id="profileimage" type="radio" value="<?php echo $stockImage->stock_image_id ?>" <?php if($cnt == 0 || $stockImage->is_profile_img == 1) { echo "checked=checked"; } ?>>
			  
			  
               <img src="<?php echo $image_path.$stockImage->image_name; ?>" style="width:50px">
            </td>
            <td class="name">
                <input type="hidden" name="image_id[]" value="<?php echo $stockImage->stock_image_id; ?>">
               <input typee="text" name="image_title[]" id="image_title<?php echo $stockImage->stock_image_id; ?>" value="<?php echo $stockImage->image_title; ?>"style="width:450px" class="basic-car-detail-textarea-small">
            </td>
            <td class="size"><span><?php echo round($filesize/1024) ?> KB</span></td>
            <td colspan="2"><a href="<?php echo $this->url('inventory',array('action' => "image-crop",'id'=>$stockImage->stock_image_id))?>">Crop</a></td>
        
        <td class="delete">
            <a href="<?php echo $this->url('inventory',array('action' => "image-delete",'id'=>$stockImage->stock_image_id))?>">
                
                <span>Delete</span>
           </td>
		   <td>
            <input type="checkbox" id="delete_image<?php echo $stockImage->stock_image_id; ?>" name="delete_image[]" value="<?php echo $stockImage->stock_image_id; ?>">
        </td>
    </tr>
	<?php $cnt++;
	} ?>
	</tbody></table>
    </form>
   
</div></div> 
        <p></p>
    </div>

	 </div>
	 </div>
</div>