<div  style="width:80%">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Notify User
        	<div>
       			
            
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
		
    </div>	
	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        
    <!-- The file upload form used as target for the file upload widget -->
    <form id="frmnotify" name="frmnotify" action="<?php echo $this->url('inventory',array('action' => "send-notification-user")) ?>" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="str_stock_id" id="str_stock_id" value="<?php echo $str_stock_id; ?>">
		<div class="basic-car-detail-header"></div>
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				
				<tr>
                	<td>
					<span class="label-text">Name: </span>
					<input type="text" name="customer_name" id="customer_name">
						
                    </td>
                </tr>
				
				<tr>
                	<td>
					<span class="label-text">Email: </span>
					<input type="text" name="customer_email" id="customer_email">
						
                    </td>
                </tr>
				
				<tr>
                	<td>
					<span class="label-text">Mobile: </span>
					<input type="text" name="customer_mobile" id="customer_mobile">
						
                    </td>
                </tr>
				
            </tbody></table>
			<input type="submit" id="save" class="add-enventry-save" value="Send">
		</div>
    </form>
   
</div>
        <p></p>
    

	 </div>
	 </div>
</div>