
 <div class="admin_menu_box">
             <div class="">
               				<div class="manage-inventory-right-panel">
   <div class="middle">

<span class="err_hide"></span>
<h3>Customer List</h3>
 <div class="tab">
    	<ul>
           <li><a style="cursor:pointer" class="active ">View</a></li>
            <li><a style="cursor:pointer" href="<?php echo $this->url('customer',array('action' => "add")) ?>" >Create</a></li>
        </ul>
    </div>	 
	
 <div class="tab-Available">
 
        <div class="add-inventory-tab-content">
	
<?php if(count($flashMessages)) : ?>
    <div class="row" >
        <div class="alert alert-success alert-dismissable">
            <button class="close" aria-hidden="true" data-dismiss="alert" type="button">
                ×
            </button>
            <ul>
                <?php foreach ($flashMessages as $msg) : ?>
                    <li><?php echo $msg; ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
<div class="grid_head">


</div>
<span class="tab_manage_container" style="display:block">
<br>
<div class="filter-header">
    <h2>Search</h2> 
        <div class="search-by-id-content">
          
        </div>
</div>
<div class="filter-search-content">
<form method="post" name="frmsearch" id="frmsearch" type="post" action="">
        <div class="mode-right-content">
            <table cellspacing="0" cellpadding="2" class="search-table-margin">
                <tbody><tr>
                    <td colspan="2">
                        <span class="select-popup-container">
                            <span class="label-text2">Date: <input type="text" name="start_date" id="start_date" value="<?php echo @$arrPost['start_date']; ?>" class="basic-car-detail-textbox"> to <input type="text" name="end_date" id="end_date" value="<?php echo @$arrPost['end_date']; ?>" class="basic-car-detail-textbox"></span>
                           
                        </span>
						 </td>

                 <td>
                        <span class="select-popup-container">
                            <span class="label-text2">Name: <input type="text" name="customer_name" id="customer_name" value="<?php echo @$arrPost['customer_name']; ?>" class="basic-car-detail-textbox"></span>
                           
                        </span>
						 </td>
                </tr> 
<tr>
                    <td>
                        <span class="select-popup-container">
                            <span class="label-text2">Mobile: <input type="text" name="customer_mobile" id="customer_mobile" value="<?php echo @$arrPost['customer_mobile']; ?>" class="basic-car-detail-textbox"></span>
                           
                        </span>
						 </td>

                 <td>
                        <span class="select-popup-container">
                            <span class="label-text2">Email: <input type="text" name="customer_email" id="customer_email" value="<?php echo @$arrPost['customer_email']; ?>" class="basic-car-detail-textbox"></span>
                           
                        </span>
						 </td>
                </tr> 
            </tbody></table>
        </div>
        <div class="high-advanced-filter" id="show">
            <input name="Submit" type="submit" value="Search" class="filter-search-icon"> 

        </div>   
</form>
    </div>

<?php if ($this->pageCount >  1): ?>
    <div class="pagination pagination-centered" width="100%">
        <ul>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('testimonial', array('action' => 'index', 'page' => $this->first, 'order_by' => $order_by, 'order' => $order,)); ?>">&laquo;</a></li>
            <li <?php echo!isset($this->previous) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('testimonial', array('action' => 'index','page' => $this->previous, 'order_by' => $order_by, 'order' => $order,)); ?>">&lsaquo;</a></li>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php echo $page == $this->current ? 'class="active"' : ''; ?>><a href="<?php echo $this->url('testimonial', array('action' => 'index','page' => $page, 'order_by' => $order_by, 'order' => $order,)); ?>">
                        <?php echo $page; ?>
                    </a></li>
            <?php endforeach; ?>

            <!-- Next page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('testimonial', array('action' => 'index','page' => $this->next, 'order_by' => $order_by, 'order' => $order,)); ?>">&rsaquo;</a></li>
            <!-- Last page link -->
            <li <?php echo!isset($this->next) ? 'class="disabled"' : ''; ?>>
                <a href="<?php echo $this->url('testimonial', array( 'action' => 'index','page' => $this->last, 'order_by' => $order_by, 'order' => $order,)); ?>">&raquo;</a></li>
        </ul>
    </div>
<?php endif; ?>
    <table class="table-content" width="100%" cellpadding="5" cellspacing="0">
<thead>
 <tr>
		<th>Customer Id</th>
        <th>Name</th>
		
		<th>Mobile</th>
		<th>Email</th>
		<th>Source</th>
		<th>D.O.B.</th>
		<th>Date</th>
        <th width="70px">Status</th>
        <th width="100px">Action</th>
</tr>
</thead>
<tbody>
 <?php
                foreach ($arrCustomer as $customer) :
            ?>
<tr>
	<td><?php echo $this->escapeHtml($customer['customer_id']);?></td>
	<td><?php echo $this->escapeHtml($customer['customer_initial']);?> <?php echo $this->escapeHtml($customer['customer_name']);?></td>
	
	<td> <?php echo $this->escapeHtml($customer['customer_mobile']);?></td>
	<td><?php echo $this->escapeHtml($customer['customer_email']);?></td>
	<td><?php echo $this->escapeHtml($customer['customer_source']);?></td>
		<td><?php echo date("d/m/Y",strtotime($customer['customer_dob']));?></td>
		<td><?php echo date("d-m-Y H:i:s",strtotime($customer['created_date']));?></td>
        <td> <?php echo $this->escapeHtml($customer['customer_status']);?></td>
        <td>
            <a href="<?php echo $this->url('customer',array('action' => "edit","id"=>$customer['cust_id'])) ?>">Edit</a> 
           
            
        </td>
        
	
</tr>
 <?php
                endforeach;
            ?>
</tbody></table>

</span>
</div>
</div>
 </div>
    
</div>
             </div>
    </div>
<script type="text/javascript">
  $(document).ready(function() {
  $('[name="start_date"]').datepicker({
            format: "yyyy-mm-dd"
        }).on('changeDate', function(e){
		$(this).datepicker('hide');
	});
  $('[name="end_date"]').datepicker({
            format: "yyyy-mm-dd"
        }).on('changeDate', function(e){
		$(this).datepicker('hide');
	});
  });

</script>