<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Update Global Variable
        	<div>
       			
             
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
     <div class="tab">
    	
    </div>	
	<div class="tab-Available">
        <div class="add-inventory-tab-content">
		<form name="frmsettings" id="frmsettings" method="POST" action="" enctype="multipart/form-data">
		
			
        <!-- Car Details -->
		
        <div class="sub-content">
		
		 
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				<?php foreach($arrSettings as $settings) { ?>
				<tr>
                	<td>					 
					<span class="label-text"><?php echo $settings['settings_name']; ?> :  </span>
					<input type="hidden" name="settings_id[]"  value="<?php echo $settings['settings_id']; ?>">
					 <input type="text" name="settings_value[]" class="jNumberonly basic-car-detail-textbox" value="<?php echo $settings['settings_value']; ?>">
                    </td>	
                </tr>
				<?php } ?>
			
            </tbody></table>
			<input type="submit" id="addimagesave" class="add-enventry-save" value="Save">
		</div>
		</form>
	 </div>
	 </div>
</div>
</div>
</div>