<link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/bottom.css">
<script src="<?php echo $this->basePath(); ?>/js/jquery-1.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/jquery.js"></script>
<script src="<?php echo $this->basePath(); ?>/js/jquery_002.js"></script>
<script language="javascript">
$(document).ready(
function (){
	$("#pikame").PikaChoose({carousel:true,carouselOptions:{wrap:'circular'}});
});
</script>
<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Inventory Images
        	<div class="add-image">
       			
              <a href="<?php echo $this->url('inventory',array('action' => "index",'id'=>'1')) ?>">Back </a> 
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;display:none;">Please Rectify The Errors In Red.</div>
		<div class="tab">
    	<ul>
           <li><a style="cursor:pointer" href="<?php echo $this->url('inventory',array('action' => "edit",'id'=>$stockid)) ?>">Car Details</a></li>
            <li><a style="cursor:pointer" class="active " >Image Manager</a></li>
        </ul>
    </div>	
	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        <div class="popup-tab popup-tab-margin">
            	<ul>
                	<li><a href="<?php echo $this->url('inventory',array('action' => "image-list",'id'=>$stockid))?>">Upload Photos</a></li>
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-sort",'id'=>$stockid))?>">Sort Photos</a></li>
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-view",'id'=>$stockid))?>">View Photos</a></li>
                </ul>
            </div> 
			<br><br>
			<br><br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="imagetag" name="imagetag" action="" method="POST" enctype="multipart/form-data">
      
      <div id="sort" class="dd_images">

</div>
<div class="btm_note">

</div>
<div class="pikachoose">
<ul id="pikame" class="jcarousel-skin-pika">
			
		<?php  
		 
		foreach($objStockImages as $stockImage) { 
			if(file_exists($config['image_absolute_path']."stock/crop/".$stockImage->image_name))
			{
				$image_path = $config['image_path']."stock/crop/";
			}
			else
			{
				$image_path = $config['image_path']."stock/";
			}
		?>
		<li>
                    
                    <img  src="<?php echo $image_path.$stockImage->image_name; ?>" ref="<?php echo $image_path.$stockImage->image_name; ?>" >
                    <span><?php echo $stockImage->image_title; ?></span>
                </li>
		
	
			<?php } ?>
	
		
		
	
	</ul>
</div>
	

</div> 
	<input type="submit" id="addinventorysave" class="add-enventry-save" value="Save">
	
    </form>
   
</div></div> 
        <p></p>
    </div>

	 </div>
	 </div>
</div>