<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Inventory Images
        	<div class="add-image">
       			
              <a href="<?php echo $this->url('inventory',array('action' => "add-image",'id'=>$stockid)) ?>">Add New Image </a> 
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;display:none;">Please Rectify The Errors In Red.</div>
		<div class="tab">
    	<ul>
           <li><a style="cursor:pointer" href="<?php echo $this->url('inventory',array('action' => "edit",'id'=>$stockid)) ?>">Car Details</a></li>
            <li><a style="cursor:pointer" class="active " >Image Manager</a></li>
        </ul>
    </div>	
	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        <div class="popup-tab popup-tab-margin">
            	<ul>
                	<li><a href="<?php echo $this->url('inventory',array('action' => "image-list",'id'=>$stockid))?>">Upload Photos</a></li>
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-sort",'id'=>$stockid))?>">Sort Photos</a></li>
                    <li id="tagphoto" class="tag-photo-btn"><a href="<?php echo $this->url('inventory',array('action' => "image-tag",'id'=>$stockid))?>">Tag Photos</a>
                    </li>
                    <li><a href="<?php echo $this->url('inventory',array('action' => "image-view",'id'=>$stockid))?>">View Photos</a></li>
                </ul>
            </div> 
			<br><br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="imagetag" name="imagetag" action="" method="POST" enctype="multipart/form-data">
      
        
        <!-- The loading indicator is shown during file processing -->
        <div class="fileupload-loading"></div>
        <br>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped" width="100%"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery">
		
		<?php  foreach($objStockImages as $stockImage) { ?>
		<tr class="template-download" style="display: table-row;">
        
            <td class="preview">
  
               <img src="<?php echo $this->basePath()."/images/stock/crop/".$stockImage->image_name; ?>" style="width:50px">
            </td>
            <td class="name">
				<input type="hidden" name="image_id[]" value="<?php echo $stockImage->stock_image_id; ?>">
               <input typee="text" name="image_title[]" id="image_title<?php echo $stockImage->stock_image_id; ?>" value="<?php echo $stockImage->image_title; ?>"style="width:450px" class="basic-car-detail-textarea-small">
            </td> 
    </tr>
	<?php } ?>
	</tbody></table>
	<input type="submit" id="addinventorysave" class="add-enventry-save" value="Save">
    </form>
   
</div></div> 
        <p></p>
    </div>

	 </div>
	 </div>
</div>