<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Hot Deal
        	<div>
       			
            
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
		
    </div>	
	
    <div class="tab-Available">
        <div class="add-inventory-tab-content">
        <div class="middle">
        
    <!-- The file upload form used as target for the file upload widget -->
    <form id="frmhotdeal" name="frmhotdeal" action="<?php echo $this->url('inventory',array('action' => "save-hot-deal")) ?>" method="POST" enctype="multipart/form-data">
        <input type="hidden" name="stock_id" id="stock_id" value="<?php echo $stock_id; ?>">
		<div class="basic-car-detail-header"></div>
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				
				<tr>
                	<td>
					<span class="label-text">Hot Deal Price: </span>
					<input type="number" name="hot_deal_price" id="hot_deal_price">
						
                    </td>
                </tr>
				
            </tbody></table>
			<input type="submit" id="save" class="add-enventry-save" value="Save">
		</div>
    </form>
   
</div>
        <p></p>
    

	 </div>
	 </div>
</div>