<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
	
<!-- Meta Tags -->
	<meta charset="utf-8">
	 <meta name="alexaVerifyID" content="B-RYFNl3nAV0RNBDsAi52Eb6j0I"/>
	 <meta name="p:domain_verify" content="29e13817c3c0e48024a49a47dcb00f9d"/>
	<!-- Favicon -->
     <?php echo $this->headTitle($arrMeta['title'])->setSeparator(' - ')->setAutoEscape(false) ?>
	 <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendName('description', $arrMeta['description'])
			->appendName('keywords', $arrMeta['keywords'])
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico')) 
		 ->prependStylesheet($this->basePath() . '/css/custom.css')
		 ->prependStylesheet($this->basePath() . '/css/list-view.css')
		 ->prependStylesheet($this->basePath() . '/css/fonts.css')
		 ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
		 ->prependStylesheet($this->basePath() . '/css/bootstrap-submenu.min.css')
		 ->prependStylesheet($this->basePath() . '/font-awesome-4.1.0/css/font-awesome.min.css' )
		 ->prependStylesheet($this->basePath() . '/fancybox/jquery.fancybox.css',"screen")
		?>
		<?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/direct_cars_custom.js')
			->prependFile($this->basePath() . '/fancybox/jquery.fancybox.pack.js')
            ->prependFile($this->basePath() . '/js/jquery-2.0.2.min.js')
			->prependFile($this->basePath() . '/js/bootstrap-submenu.js')
			
		
		?>
		<script type="text/javascript" async defer
		  src="https://apis.google.com/js/platform.js?publisherid=109036767011856747432">
		</script>
       </head>
    <body>
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-M8ZTM9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M8ZTM9');</script>
<!-- End Google Tag Manager -->



	<div class="wrapper <?php if(@$breadcrum != 'Home' && @$breadcrum != 'Why Direct Cars' && @$breadcrum != 'Privacy Policy')  { ?>sell-car<?php } ?>">
		<div class="header">
		
		<div class="top-bar">
		
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
					
					<h1>Welcome to Direct Cars-Great Way to Buy & Sell Used Cars in Gurgaon, Delhi/NCR</h1>
					
					</div>
						<div id='cse'class="col-sm-4">Loading</div>
<script src='//www.google.com/jsapi' type='text/javascript'></script>
<script type='text/javascript'>
google.load('search', '1', {language: 'en', style: google.loader.themes.V2_DEFAULT});
google.setOnLoadCallback(function() {
  var customSearchOptions = {};
  var orderByOptions = {};
  orderByOptions['keys'] = [{label: 'Relevance', key: ''} , {label: 'Date', key: 'date'}];
  customSearchOptions['enableOrderBy'] = true;
  customSearchOptions['orderByOptions'] = orderByOptions;
  var imageSearchOptions = {};
  imageSearchOptions['layout'] = 'google.search.ImageSearch.LAYOUT_POPUP';
  customSearchOptions['enableImageSearch'] = true;
  var customSearchControl =   new google.search.CustomSearchControl('003119325336657268206:evhv9cbvgeq', customSearchOptions);
  customSearchControl.setResultSetSize(google.search.Search.SMALL_RESULTSET);
  var options = new google.search.DrawOptions();
  options.setAutoComplete(true);
  customSearchControl.draw('cse', options);
}, true);
</script>

<style type='text/css'>
  .gsc-control-cse {
    font-family: Arial, sans-serif;
   background-color: inherit;
   border:0;
   padding:0;
  }
  .gsc-control-cse .gsc-table-result {
    font-family: Arial, sans-serif;
  }
  input.gsc-input, .gsc-input-box, .gsc-input-box-hover, .gsc-input-box-focus {
    border-color: #D9D9D9;
  }
  input.gsc-search-button, input.gsc-search-button:hover, input.gsc-search-button:focus {
    border-color: #FFFFFF;
    background-color: #373737;
    background-image: none;
    filter: none;
	display: none;

  }
  .gsc-tabHeader.gsc-tabhInactive {
    border-color: #FF9900;
    background-color: #FFFFFF;
  }
  .gsc-tabHeader.gsc-tabhActive {
    border-color: #E9E9E9;
    background-color: #E9E9E9;
    border-bottom-color: #FF9900
  }
  .gsc-tabsArea {
    border-color: #FF9900;
  }
  .gsc-webResult.gsc-result, .gsc-results .gsc-imageResult {
    border-color: #FFFFFF;
    background-color: #FFFFFF;
  }
  .gsc-webResult.gsc-result:hover, .gsc-imageResult:hover {
    border-color: #FFFFFF;
    background-color: #FFFFFF;
  }
  .gs-webResult.gs-result a.gs-title:link, .gs-webResult.gs-result a.gs-title:link b, .gs-imageResult a.gs-title:link, .gs-imageResult a.gs-title:link b  {
    color: #0000CC;
  }
  .gs-webResult.gs-result a.gs-title:visited, .gs-webResult.gs-result a.gs-title:visited b, .gs-imageResult a.gs-title:visited, .gs-imageResult a.gs-title:visited b {
    color: #0000CC;
  }
  .gs-webResult.gs-result a.gs-title:hover, .gs-webResult.gs-result a.gs-title:hover b, .gs-imageResult a.gs-title:hover, .gs-imageResult a.gs-title:hover b {
    color: #0000CC;
  }
  .gs-webResult.gs-result a.gs-title:active, .gs-webResult.gs-result a.gs-title:active b, .gs-imageResult a.gs-title:active, .gs-imageResult a.gs-title:active b {
    color: #0000CC;
  }
  .gsc-cursor-page {
    color: #0000CC;
  }
  .gsib_a {
	  padding:0;
  }
  a.gsc-trailing-more-results:link {
    color: #0000CC;
  }
  .gs-webResult .gs-snippet, .gs-imageResult .gs-snippet, .gs-fileFormatType {
    color: #000000;
  }
  .gs-webResult div.gs-visibleUrl, .gs-imageResult div.gs-visibleUrl {
    color: #008000;
  }
  .gs-webResult div.gs-visibleUrl-short {
    color: #008000;
  }
  .gs-webResult div.gs-visibleUrl-short  {
    display: none;
  }
  .gs-webResult div.gs-visibleUrl-long {
    display: block;
  }
  .gs-promotion div.gs-visibleUrl-short {
    display: none;
  }
  .gs-promotion div.gs-visibleUrl-long  {
    display: block;
  }
  .gsc-cursor-box {
    border-color: #FFFFFF;
  }
  .gsc-results .gsc-cursor-box .gsc-cursor-page {
    border-color: #E9E9E9;
    background-color: #FFFFFF;
    color: #0000CC;
  }
  .gsc-results .gsc-cursor-box .gsc-cursor-current-page {
    border-color: #FF9900;
    background-color: #FFFFFF;
    color: #0000CC;
  }
  .gsc-webResult.gsc-result.gsc-promotion {
    border-color: #336699;
    background-color: #FFFFFF;
  }
  .gsc-completion-title {
    color: #0000CC;
  }
  .gsc-completion-snippet {
    color: #000000;
  }
  .gs-promotion a.gs-title:link,.gs-promotion a.gs-title:link *,.gs-promotion .gs-snippet a:link  {
    color: #0000CC;
  }
  .gs-promotion a.gs-title:visited,.gs-promotion a.gs-title:visited *,.gs-promotion .gs-snippet a:visited {
    color: #0000CC;
  }
  .gs-promotion a.gs-title:hover,.gs-promotion a.gs-title:hover *,.gs-promotion .gs-snippet a:hover  {
    color: #0000CC;
  }
  .gs-promotion a.gs-title:active,.gs-promotion a.gs-title:active *,.gs-promotion .gs-snippet a:active {
    color: #0000CC;
  }
  .gs-promotion .gs-snippet, .gs-promotion .gs-title .gs-promotion-title-right, .gs-promotion .gs-title .gs-promotion-title-right * {
    color: #000000;
  }
  .gs-promotion .gs-visibleUrl,.gs-promotion .gs-visibleUrl-short  {
    color: #008000;
  }
</style>
					<ul class="social_icons pull-right col-sm-2 text-right mobile-hide">
						<li><a class="btn btn-primary social-login-btn social-google" href="https://plus.google.com/+DIRECTCARSGurgaon/about" target="NEW"><i class="fa fa-google-plus"></i></a></li>
						<li><a class="btn btn-primary social-login-btn social-facebook" href="https://www.facebook.com/directcars.in" target="NEW"> <i class="fa fa-facebook"></i></a></li>
						<li><a class="btn btn-primary social-login-btn social-twitter" href="https://twitter.com/directcarsindia" target="NEW"><i class="fa fa-twitter"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="clear"></div>
		<nav class="navbar navbar-bootsnipp animate" role="navigation">
		
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
	
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="animbrand">
        <a class="navbar-brand animate" href="/"><img src="<?php echo $this->basePath();?>/images/logo.png" alt="Direct Cars-Great Way to Buy and Sell Used Cars"/></a>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">
       <li class=""><a href="/" class="animate">Home</a></li>
		<li class=""><a href="<?php echo $this->url('usedcar',array('action' => "sell")); ?>" class="animate">Sell Your Car</a></li>
		<li class=""><a href="<?php echo $this->url('usedcar',array('action' => "search")); ?>" class="animate">Buy Used Car</a></li>
		<li class="dropdown"><a ria-expanded="false" tabindex="0" data-toggle="dropdown" data-submenu="" class="animate">Showrooms <span class="caret"></a>
		<ul class="dropdown-menu">
		<?php foreach($arrShowroomMaster as  $hd_showroom) { ?>
			<li><a href="<?php echo $this->url('showroom',array('action' => "index",'id'=>$hd_showroom['showroom_id'],'name' => strtolower(str_replace(" ","+",$hd_showroom['showroom_name'])),'city' =>strtolower($hd_showroom['city']))); ?>" tabindex="0"><?php echo $hd_showroom['showroom_name']; ?></a></li>
		<?php } ?>
		  </ul>
		</li>
        <li class=""><a href="<?php echo $this->url('index',array('action' => "why-us")); ?>" class="animate">Why Direct Cars</a></li>
        <li class=""><a href="http://directcars.in/blog/customer-center" class="animate" target="_blank">Customer Center</a></li>
		<li class=""><a href="http://directcars.in/blog" class="animate" target="_blank">Our Blog</a></li>
        
      </ul>
    </div>
  </div>
</nav>
	<div class="breadcrum"> 
		<div class="container">
			<div class="col-md-5 breadcrum-inner mobile-hide"><?php echo @$breadcrum; ?></div>
			<div class="col-sm-7 col-lg-7 col-md-12 pull-right">
				<ul class="info pull-right">
					<li class="mobile-hide"><span class="icon-executive"></span></li>
					<li class="mobile-hide">For Assistance</li>
					<li><a href="mailto:<?php echo $arrSettings[0]['settings_value']; ?>"><i class="fa fa-envelope-o"></i> <?php echo $arrSettings[0]['settings_value']; ?></a></li>
					<li><i class="fa fa-mobile"></i> <?php echo $arrSettings[1]['settings_value']; ?></li>
				</ul>
			</div>
		</div>
	</div>
		</div>
		<!-- end header -->
		
	<?php echo $this->content; ?>
		<!-- footer -->
		<div class="footer">
			<div class="container">
				<div class="col-sm-4 site-links">
					<h3 class="title"><strong>Site</strong> links</h3>
					<ul>
						<li><b class="right-caret"></b> <a href="/">Home</a></li>
						<li><b class="right-caret"></b> <a href="<?php echo $this->url('usedcar',array('action' => "sell")); ?>">Sell your car</a></li>
						<li><b class="right-caret"></b> <a href="<?php echo $this->url('usedcar',array('action' => "search")); ?>">Buy used cars</a></li>
						<li class="dropdown-submenu" style="width:40%;cursor:pointer"><b class="right-caret"></b> <a ria-expanded="true" tabindex="0" data-toggle="dropdown" data-submenu="">Showrooms</a>
						<ul class="dropdown-menu">
						<?php foreach($arrShowroomMaster as  $hd_showroom) { ?>
							<li><a href="<?php echo $this->url('showroom',array('action' => "index",'id'=>$hd_showroom['showroom_id'],'name' => strtolower(str_replace(" ","+",$hd_showroom['showroom_name'])),'city' =>strtolower($hd_showroom['city']))); ?>" tabindex="0"><?php echo $hd_showroom['showroom_name']; ?></a></li>
						<?php } ?>
						  </ul></li>
						<li><b class="right-caret"></b> <a href="<?php echo $this->url('index',array('action' => "why-us")); ?>">Why Direct Cars</a></li>
					</ul>
				</div>
				<div class="col-sm-4 contact-detail">
					<h3 class="title"><strong>Contact</strong> info</h3>
					
					<p class="marginT10"><span>Phone:</span> <i class="fa fa-mobile"></i> <?php echo $arrSettings[1]['settings_value']; ?></p>
					<p><span>Email:</span> <a href="mailto:<?php echo $arrSettings[0]['settings_value']; ?>"><?php echo $arrSettings[0]['settings_value']; ?></a></p>
					<?php $arrDays = explode(",",$arrShowroomMaster[0]['showroom_timings_days']); ?>
					<p class="marginT10"><span>Working days :</span> <?php if(count($arrDays )== 7) { ?>
						 We are OPEN 7 days a week
						<?php } else {?>
						We are OPEN ON <?php echo str_replace(",",", ",$arrShowroomMaster[0]['showroom_timings_days']); ?>
						<?php } ?> </p>
					<p><span>Timing : </span><?php echo $arrShowroomMaster[0]['showroom_timings_start']; ?> to <?php echo $arrShowroomMaster[0]['showroom_timings_end']; ?></p>
				</div>
				<div class="col-sm-4">
					<h3 class="title"><strong>Social</strong> links</h3>
					<ul class="social_icons">
					<li><a class="btn btn-primary social-login-btn social-facebook" href="https://www.facebook.com/directcars.in" target="NEW"><i class="fa fa-facebook"></i></a></li>
					<li><a class="btn btn-primary social-login-btn social-google" href="https://plus.google.com/+DIRECTCARSGurgaon/about" target="NEW"> <i class="fa fa-google-plus"></i></a></li>
					<li><a class="btn btn-primary social-login-btn social-twitter" href="https://twitter.com/directcarsindia" target="NEW"> <i class="fa fa-twitter"></i></a></li>
				  </ul>
				</div>
			</div>
			<div class="callus">
				<div class="container">
					<div class="col-sm-4"><a href="#"><img src="<?php echo $this->basePath();?>/images/logo.png" alt="Direct Cars-Great Way to Buy and Sell Used Cars"/></a></div>
					<div class="col-sm-8 pull-right text-right footer-call"><span>TO BUY CALL: <i class="fa fa-mobile"></i> <?php echo $arrShowroomMaster[0]['phone_1']; ?> </span>    <span>TO SELL CALL: <i class="fa fa-mobile"></i> <?php if($arrShowroomMaster[0]['phone_2'] != "") echo $arrShowroomMaster[0]['phone_2']; else echo $arrShowroomMaster[0]['phone_1']; ?></span></div>
				</div>
			</div>
		</div>
		<div class="copywright">
			<div class="container text-center">© Direct Cars Pvt. Ltd. 2015 | <a href="<?php echo $this->url('index',array('action' => "privacy")); ?>" target="_blank">Privacy Policy</a></div>
		</div>
		
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-60735700-1', 'auto');
	  ga('send', 'pageview');

	</script>
<!-- Google Code for Phone Calls Conversion Page
In your html page, add the snippet and call
goog_report_conversion when someone clicks on the
phone number link or button. -->
<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 968035675;
    w.google_conversion_label = "eRP9CJmd_FoQ25rMzQM";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    window.google_is_call = true;
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>	
<script src="//scripts.whatconverts.com/profile/51467.js"></script>
	</div>
		<script src="<?php echo $this->basePath();?>/js/bootstrap.min.js" type="text/javascript"></script>
    </body>
</html>