<?php echo $this->doctype(); ?>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Direct Cars '. $this->translate('Direct Cars'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        //->prependStylesheet($this->basePath() . '/css/style.css')
						 ->prependStylesheet($this->basePath() . '/css/jquery.Jcrop.css')
						 ->prependStylesheet($this->basePath() . '/css/main.css')
						 ->prependStylesheet($this->basePath() . '/fancybox/jquery.fancybox.css')
						//->prependStylesheet($this->basePath() . '/css/datepicker.css')
                        //->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/fancybox/jquery.fancybox.pack.js')
			->prependFile($this->basePath() . '/js/jquery.Jcrop.js')
			->prependFile($this->basePath() . '/js/direct_cars_custom.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basePath() . '/js/jquery.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
   <body>
  <div id="main">
    <div class="header">
      <div class="header-left">
        <img src="<?php echo $this->basePath(); ?>/images/logo.jpg" alt="" />
      </div>
        <div class="header-right">
        <div class="header_admin">
         <img src="<?php echo $this->basePath(); ?>/images/admin_img.jpg" alt="" align="absbottom" />
         <h1>Hello Admin Panel</h1>
      </div>
      </div>
        <br />
		 <div id="greenbg" style="color:#fff;">
		
		
	<div style="float:left; width:60%; margin-top: 16px; padding-left: 20px; color:#ccc;">
	<?php if($this->ZfcUserIdentity()) { ?> 
		<a href="#">Dashboard</a> | 
		<a href="<?php echo $this->url('inventory',array('action' => "add")) ?>">Add Inventory </a>  |
		<a href="<?php echo $this->url('inventory',array('action' => "index",'id'=>'1')) ?>">Manage Inventory </a> |
		<a href="<?php echo $this->url('mmv') ?>">Manage MMV </a> |
		<a href="<?php echo $this->url('testimonial') ?>">Testimonial </a> |
		<a href="<?php echo $this->url('showroom') ?>">Showroom </a> |
		<?php if($this->ZfcUserIdentity()->getIsAdmin()) { ?>
		<a href="<?php echo $this->url('adminuser') ?>">Manage User </a> |	
		<a href="<?php echo $this->url('zfcuser/register') ?>">Add User </a>
		<?php } }?>
	</div>
    <?php if ($this->zfcUserDisplayName() != ''){ ?>
	<div style="float:right; width:35%"><p>Welcome <?php echo $this->zfcUserDisplayName() ?>,<a href="<?php echo $this->basePath();?>/user/change-password" class="greenbg14">Change Pass</a>, <a href="<?php echo $this->url('zfcuser/logout') ?>" class="greenbg14">Logout</a></p></div>
	<?php }  ?>
    </div>
   </div>
    <?php echo $this->content; ?>
        <div class="footer">
         <p>
              
            
             Copyright© 2014, Direct Cars Pvt Ltd. <a href="#" class="terms">Disclaimer</a> | <a href="#" class="terms">Privacy Policy </a>  
            </p> 
        </div>
  </div>
</body>
</html>
