<?php
namespace Rctransfer\Model;

class RcTransfer
{
    public $rc_transfer_id;
    public $stock_id;	
	public $seller_id;
	public $original_rc_file;	
	public $original_rc_file_status;	
	public $original_rc_date;
	public $insurance_file;	
	public $insurance_file_status;
    public $insurance_date;	
	public $tto_set_file;
	public $tto_set_file_status;	
	public $tto_set_date;	
	public $form35_file;
    public $form35_file_status;	
	public $form35_date;
	public $affidavit_file;	
	public $affidavit_file_status;	
	public $affidavit_date;
	public $letter_head_file;	
	public $letter_head_file_status;
    public $letter_head_date;	
	public $id_proof_1_file;
	public $id_proof_1_file_status;	
	public $id_proof_1_date;	
	public $id_proof_2_file;
    public $id_proof_2_file_status;	
	public $id_proof_2_date;
	public $address_proof_1_file;	
	public $address_proof_1_file_status;	
	public $address_proof_1_date;
	public $address_proof_2_file;	
	public $address_proof_2_file_status;
    public $address_proof_2_date;	
	public $buyer_id;
	public $buyer_id_proof_1_file;	
	public $buyer_id_proof_1_file_status;	
	public $buyer_id_proof_1_date;
    public $buyer_id_proof_2_file;	
	public $buyer_id_proof_2_file_status;
	public $buyer_id_proof_2_date;	
	public $buyer_address_proof_1_file;	
	public $buyer_address_proof_1_file_status;
	public $buyer_address_proof_1_date;	
	public $buyer_address_proof_2_file;
    public $buyer_address_proof_2_file_status;	
	public $buyer_address_proof_2_date;
	public $puc_file;	
	public $puc_file_status;	
	public $puc_date;
    public $transfer_by;	
	public $transfer_type;
	public $transfer_from;	
	public $transfer_to;	
	public $duplicate_rc;
	public $hpa;	
	public $buyer_financiers_name;
    public $cng_addition;	
	public $cng_vendor;
	public $file_status;	
	public $login_date;	
	public $login_remarks;	
	public $agent_id;
	public $transfer_status;	
	public $transfer_date;
    public $transfer_file;	
	public $discrepency_details;
	public $resubmission_date;	
	public $resubmission_remarks;	
	public $created_date;
	
    public function exchangeArray($data)
    {
		$this->rc_transfer_id		= (isset($data['rc_transfer_id'])) ? $data['rc_transfer_id'] : null;
		$this->stock_id	= (isset($data['stock_id'])) ? $data['stock_id'] : null;
		$this->seller_id	= (isset($data['seller_id'])) ? $data['seller_id'] : null;
		$this->original_rc_file		= (isset($data['original_rc_file'])) ? $data['original_rc_file'] : null;
		$this->original_rc_file_status	= (isset($data['original_rc_file_status'])) ? $data['original_rc_file_status'] : null;
		$this->original_rc_date		= (isset($data['original_rc_date'])) ? $data['original_rc_date'] : null;
		$this->insurance_file		= (isset($data['insurance_file'])) ? $data['insurance_file'] : null;
		$this->insurance_file_status		= (isset($data['insurance_file_status'])) ? $data['insurance_file_status'] : null;
		$this->insurance_date	= (isset($data['insurance_date'])) ? $data['insurance_date'] : null;
		$this->tto_set_file	= (isset($data['tto_set_file'])) ? $data['tto_set_file'] : null;
		$this->tto_set_file_status		= (isset($data['tto_set_file_status'])) ? $data['tto_set_file_status'] : null;
		$this->tto_set_date	= (isset($data['tto_set_date'])) ? $data['tto_set_date'] : null;
		$this->form35_file		= (isset($data['form35_file'])) ? $data['form35_file'] : null;
		$this->form35_file_status	= (isset($data['form35_file_status'])) ? $data['form35_file_status'] : null;
		$this->form35_date	= (isset($data['form35_date'])) ? $data['form35_date'] : null;
		$this->affidavit_file		= (isset($data['affidavit_file'])) ? $data['affidavit_file'] : null;
		$this->affidavit_file_status	= (isset($data['affidavit_file_status'])) ? $data['affidavit_file_status'] : null;
		$this->affidavit_date		= (isset($data['affidavit_date'])) ? $data['affidavit_date'] : null;
		$this->letter_head_file		= (isset($data['letter_head_file'])) ? $data['letter_head_file'] : null;
		$this->letter_head_file_status		= (isset($data['letter_head_file_status'])) ? $data['letter_head_file_status'] : null;
		$this->letter_head_date	= (isset($data['letter_head_date'])) ? $data['letter_head_date'] : null;
		$this->id_proof_1_file	= (isset($data['id_proof_1_file'])) ? $data['id_proof_1_file'] : null;
		$this->id_proof_1_file_status		= (isset($data['id_proof_1_file_status'])) ? $data['id_proof_1_file_status'] : null;
		$this->id_proof_1_date	= (isset($data['id_proof_1_date'])) ? $data['id_proof_1_date'] : null;
		$this->id_proof_2_file		= (isset($data['id_proof_2_file'])) ? $data['id_proof_2_file'] : null;
		$this->id_proof_2_file_status	= (isset($data['id_proof_2_file_status'])) ? $data['id_proof_2_file_status'] : null;
		$this->id_proof_2_date	= (isset($data['id_proof_2_date'])) ? $data['id_proof_2_date'] : null;
		$this->address_proof_1_file		= (isset($data['address_proof_1_file'])) ? $data['address_proof_1_file'] : null;
		$this->address_proof_1_file_status	= (isset($data['address_proof_1_file_status'])) ? $data['address_proof_1_file_status'] : null;
		$this->address_proof_1_date		= (isset($data['address_proof_1_date'])) ? $data['address_proof_1_date'] : null;
		$this->address_proof_2_file		= (isset($data['address_proof_2_file'])) ? $data['address_proof_2_file'] : null;
		$this->address_proof_2_file_status		= (isset($data['address_proof_2_file_status'])) ? $data['address_proof_2_file_status'] : null;
		$this->address_proof_2_date	= (isset($data['address_proof_2_date'])) ? $data['address_proof_2_date'] : null;
		$this->buyer_id	= (isset($data['buyer_id'])) ? $data['buyer_id'] : null;
		$this->buyer_id_proof_1_file		= (isset($data['buyer_id_proof_1_file'])) ? $data['buyer_id_proof_1_file'] : null;
		$this->buyer_id_proof_1_file_status	= (isset($data['buyer_id_proof_1_file_status'])) ? $data['buyer_id_proof_1_file_status'] : null;
		$this->buyer_id_proof_1_date		= (isset($data['buyer_id_proof_1_date'])) ? $data['buyer_id_proof_1_date'] : null;
		$this->buyer_id_proof_2_file	= (isset($data['buyer_id_proof_2_file'])) ? $data['buyer_id_proof_2_file'] : null;
		$this->buyer_id_proof_2_file_status	= (isset($data['buyer_id_proof_2_file_status'])) ? $data['buyer_id_proof_2_file_status'] : null;
		$this->buyer_id_proof_2_date		= (isset($data['buyer_id_proof_2_date'])) ? $data['buyer_id_proof_2_date'] : null;
		$this->buyer_address_proof_1_file	= (isset($data['buyer_address_proof_1_file'])) ? $data['buyer_address_proof_1_file'] : null;
		$this->buyer_address_proof_1_file_status		= (isset($data['buyer_address_proof_1_file_status'])) ? $data['buyer_address_proof_1_file_status'] : null;
		$this->buyer_address_proof_1_date		= (isset($data['buyer_address_proof_1_date'])) ? $data['buyer_address_proof_1_date'] : null;
		$this->buyer_address_proof_2_file		= (isset($data['buyer_address_proof_2_file'])) ? $data['buyer_address_proof_2_file'] : null;
		$this->buyer_address_proof_2_file_status	= (isset($data['buyer_address_proof_2_file_status'])) ? $data['buyer_address_proof_2_file_status'] : null;
		$this->buyer_address_proof_2_date	= (isset($data['buyer_address_proof_2_date'])) ? $data['buyer_address_proof_2_date'] : null;
		$this->puc_file		= (isset($data['puc_file'])) ? $data['puc_file'] : null;
		$this->puc_file_status	= (isset($data['puc_file_status'])) ? $data['puc_file_status'] : null;
		$this->puc_date	= (isset($data['puc_date'])) ? $data['puc_date'] : null;
		$this->transfer_by		= (isset($data['transfer_by'])) ? $data['transfer_by'] : null;
		$this->transfer_type	= (isset($data['transfer_type'])) ? $data['transfer_type'] : null;
		$this->transfer_from		= (isset($data['transfer_from'])) ? $data['transfer_from'] : null;
		$this->transfer_to	= (isset($data['transfer_to'])) ? $data['transfer_to'] : null;
		$this->duplicate_rc	= (isset($data['duplicate_rc'])) ? $data['duplicate_rc'] : null;
		$this->hpa		= (isset($data['hpa'])) ? $data['hpa'] : null;
		$this->buyer_financiers_name	= (isset($data['buyer_financiers_name'])) ? $data['buyer_financiers_name'] : null;
		$this->cng_addition		= (isset($data['cng_addition'])) ? $data['cng_addition'] : null;
		$this->cng_vendor		= (isset($data['cng_vendor'])) ? $data['cng_vendor'] : null;
		$this->file_status		= (isset($data['file_status'])) ? $data['file_status'] : null;
		$this->login_date	= (isset($data['login_date'])) ? $data['login_date'] : null;
		$this->login_remarks	= (isset($data['login_remarks'])) ? $data['login_remarks'] : null;
		$this->agent_id		= (isset($data['agent_id'])) ? $data['agent_id'] : null;
		$this->transfer_status	= (isset($data['transfer_status'])) ? $data['transfer_status'] : null;
		$this->transfer_date		= (isset($data['transfer_date'])) ? $data['transfer_date'] : null;
		$this->transfer_file	= (isset($data['transfer_file'])) ? $data['transfer_file'] : null;
		$this->discrepency_details		= (isset($data['discrepency_details'])) ? $data['discrepency_details'] : null;
		$this->resubmission_date		= (isset($data['resubmission_date'])) ? $data['resubmission_date'] : null;
		$this->resubmission_remarks		= (isset($data['resubmission_remarks'])) ? $data['resubmission_remarks'] : null;
		$this->created_date	= (isset($data['created_date'])) ? $data['created_date'] : null;
    }
}