<div class="admin_menu_box">
      
            
             <div class="">
               <div class="manage-inventory-right-panel">
	<h1>
		Manage Showroom
        	<div class="add-image">
       			
              <a href="<?php echo $this->url('showroom') ?>">Back </a> 
        </div>
    </h1>
		<div class="errortopdiv" style="color: red; text-align: center; width: 100%;"><?php print_r(@$flashMessages[0]); ?></div>
     <div class="tab">
    	
    </div>	
	<div class="tab-Available">
        <div class="add-inventory-tab-content">
		<?php $form->prepare(); // The correct enctype is set here ?>
		<?php echo $this->form()->openTag($form); ?>
			<input type="hidden" name="showroom_id" id="showroom_id" value="">
        <!-- Car Details -->
		<input type="submit" id="addimagesave1" class="add-enventry-save" value="Save">
		
        <div class="sub-content">
		
		 
            <table cellpadding="12" cellspacing="0">
            	<tbody>
				
				<tr>
                	<td>					 
					<span class="label-text">Showroom Name: </span>
					 <?php echo $this->formText($form->get('showroom_name')); ?>	
                    </td>
				
                	<td>					 
					<span class="label-text">Address1: </span>
					 <?php echo $this->formText($form->get('address_line_1')); ?>
					 </td>
					 <td>
					 <span class="label-text">Address2: </span>
					 <?php echo $this->formText($form->get('address_line_2')); ?>	
                    </td>
					
               </tr>
				<tr>
                	<td>					 
					<span class="label-text">Land Mark: </span>
					 <?php echo $this->formText($form->get('land_mark')); ?>	
                    </td>
					
                
                	<td>					 
					<span class="label-text">Locality: </span>
					 <?php echo $this->formText($form->get('locality')); ?>	
                    </td>
					<td>					 
					<span class="label-text">Country: </span>
					 <?php echo $this->formText($form->get('country')); ?>	
                    </td>
               
					
                </tr>
				<tr>
                	<td>					 
					<span class="label-text">State: </span>
					 <?php echo $this->formSelect($form->get('state')); ?>	
                    </td>
					
					
                	<td>					 
					<span class="label-text">City: </span>
					 <?php echo $this->formSelect($form->get('city')); ?>	
                    </td>
              
                	<td>					 
					<span class="label-text">Pin Code: </span>
					 <?php echo $this->formText($form->get('pin_code')); ?>	
                    </td>
					
               </tr>
				<tr>
                	<td>					 
					<span class="label-text">Google Link: </span>
					 <?php echo $this->formText($form->get('google_link')); ?>	
                    </td>
					
               
                	<td>					 
					<span class="label-text">Google Map Code: </span>
					 <?php echo $this->formText($form->get('google_map_code')); ?>	
                    </td>
				</tr>
				<tr>
					<td>					 
					<span class="label-text">Manager Name: </span>
					 <?php echo $this->formText($form->get('manager_name')); ?>	
                    </td>
                	<td>					 
					<span class="label-text">Primary Phone: </span>
					 <?php echo $this->formText($form->get('phone_1')); ?>	
                    </td>

               
                	<td>					 
					<span class="label-text">Secondary Phone: </span>
					 <?php echo $this->formText($form->get('phone_2')); ?>	
                    </td>
					
					</tr>
				<tr>
                	<td>					 
					<span class="label-text">Primary Email: </span>
					 <?php echo $this->formEmail($form->get('email')); ?>	
                    </td>
					
               
                	<td>					 
					<span class="label-text">Secondary Email: </span>
					 <?php echo $this->formEmail($form->get('secondary_email')); ?>	
                    </td>
					
                </tr>
				<tr>
                	
					
               
                	<td colspan="3">					 
					<span class="label-text">Description: </span>
					 <?php echo $this->formTextArea($form->get('description')); ?>	
                    </td>
					
                </tr>
				<tr>
					<td>					 
					<span class="label-text">Services: </span>
					 <?php echo $this->formText($form->get('services')); ?>	
                    </td>
                	<td>
					
					<span class="label-text">Virtual Tour Vedio*: </span>
					<?php echo $this->formText($form->get('virtual_tour_video')); ?>	
						
                    </td>
				
                	<td>					 
					
                    </td>
					
                </tr>
				
                <tr>
					<td colspan="3">
					<span class="label-text">Showroom Timings: </span>
					<script type="text/javascript" src="<?php echo $this->basePath()?>/js/bootstrap-multiselect.js"></script>
<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/bootstrap-multiselect.css" type="text/css"/>
		
		
<?php echo $this->formSelect($form->get('showroom_timings_days')); ?>	
<script type="text/javascript">
$(document).ready(function() {
//$('#showroom_timings_days').multiselect();
 $('#showroom_timings_days').multiselect({
includeSelectAllOption: true,
//enableFiltering: true
});
});
</script>

					 <?php echo $this->formText($form->get('showroom_timings_start')); ?> - <?php echo $this->formText($form->get('showroom_timings_end')); ?>		
					</td>
				</tr>
            </tbody></table>
			<input type="submit" id="addimagesave" class="add-enventry-save" value="Save">
		</div>
		<?php echo $this->form()->closeTag(); ?>
	 </div>
	 </div>
</div>
</div>
</div>